services:
  - type: web
    name: nsimbi-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: IS_POSTGRES
        value: true
      - key: DB_NAME
        fromDatabase:
          name: nsimbi-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: nsimbi-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nsimbi-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: nsimbi-db
          property: host
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: nsimbi-db
    plan: free
    databaseName: nsimbi_db
    user: nsimbi_user
